### ISSUE TITLE
Add donation link to plugin page

### ISSUE THREAD

**Issue by danmoz** [cemilbrowne/homebridge-airtouch5-platform#11]
The plugin config allows you to [configure a donation link](https://github.com/homebridge/homebridge/wiki/Donation-Links) that appears in the Homebridge UI.

I just could not be happier that this plugin lets me use my Airtouch system with voice control. If such a link existed, I would use it.

**Comment by cemilbrowne** [comment]
Thanks @danmoz - appreciate the sentiment. I'm really just happy people use it.  I wrote it for me, and TBH, just rock on!
