### ISSUE TITLE
Temperature input

### ISSUE THREAD

**Issue by davidbanham** [cemilbrowne/homebridge-airtouch5-platform#3]
Thanks for the plugin! It's working great for me.

I'm working on a way to control the temperature of individual zones based on temperature data reported by external sensors. At the moment, this is an external process that polls the sensors and then sets the damper percentage in the zone to suit.

A much neater solution would be to poll the sensors then just feed those temperatures into the AirTouch and let it figure out the targeting. Basically, simulating the first-party temp sensors you can buy with existing hardware.

The question is, though, what are the magic bytes to set the temp for a zone? I haven't been able to find any protocol documentation for the airtouch 5. I was wondering if you had a source for some or had sniffed some traffic between the proprietary sensors and the unit?

**Comment by cemilbrowne** [comment]
Hey David, sorry for the late response.  I'll attach the docco.  
[AirTouch.5.Communication.ProtocolV1.1.pdf](https://github.com/cemilbrowne/homebridge-airtouch5-platform/files/13065091/AirTouch.5.Communication.ProtocolV1.1.pdf)

**Comment by davidbanham** [comment]
No worries and thanks! Unfortunately that doc doesn't contain anything about the protocol between the sensors and the control unit. Short of reverse engineering I don't think there's any way to feed our own sensor data directly into the airtouch controller. I guess they'd rather people spend $150!

**Comment by cemilbrowne** [comment]
Hi David,

Sorry, I misread your ask - having seen anything around that comms protocol.  They definitely want you to use their sensors.  I could probably pop one open and find something straighforward in there, though...
