### ISSUE TITLE
Airtouch 4

### ISSUE THREAD

**Issue by BeemerM2** [cemilbrowne/homebridge-airtouch5-platform#4]
**Describe Your Problem:**
 I enter  10.0.0.62 which is where my controller is connected but always get error message
Done everything you have suggested but won’t work

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by BeemerM2** [comment]
Can you help?
Please

**Comment by BeemerM2** [comment]
Sorry 192.168.0.1 and it added ok but that's all it does. Nothing comes up to enable it to be used?

**Comment by cemilbrowne** [comment]
Sorry; this only supports airtouch5.
